version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next-pwa
    versions:
    - 5.2.3
    - 5.2.5
    - 5.2.9
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.5
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.5
